Altinn/altinn-receipt

- .github/workflows/build-and-analyze.yml
- src/backend/Altinn.Receipt/Altinn.Platform.Receipt.csproj
- src/backend/Altinn.Receipt/Program.cs
> replaced deprecated Azure dependencies

- Dockerfile
- src/frontend/Dockerfile
- src/frontend/package.json
- src/frontend/yarn.lock
Update major-version to frontend modules
- msw to v0.49.0
- babel-loader to v9
- jest-junit to v15
- webpack-cli to v5
- node.js to v19 (latest)
- Altinn/altinn-platform#249
> chore(deps): update dependency frontend modules

- src/frontend/src/utils/language.ts
- src/frontend/src/utils/receipt.ts
This change reflects the changes in app-frontend, see the linked issue for further explanation. I ran the receipt application locally and confirmed that it works the same way as in app-frontend.
- Many of the code-changes are due to prettier format
- https://github.com/Altinn/app-frontend-react/pull/1058
> Added support for `appReceiver` textresource

- Dockerfile
- src/backend/Altinn.Receipt/Altinn.Platform.Receipt.csproj
- test/Altinn.Platform.Receipt.Tests.csproj
> upgrade backend to .net 7

- Dockerfile
- src/backend/Altinn.Receipt/Altinn.Platform.Receipt.csproj
- test/Altinn.Platform.Receipt.Tests.csproj
> patching w24

- .github/workflows/build-and-analyze-fork.yml
- .github/workflows/build-and-analyze.yml
I forgot to update workflows after changing the name of the solution file. 
- #182
> Solution name was changed to Altinn.Receipt.sln

- .github/workflows/build-and-analyze-fork.yml
- .github/workflows/build-and-analyze.yml
- .github/workflows/codeql-analysis.yml
- Dockerfile
- src/backend/Altinn.Receipt/Altinn.Platform.Receipt.csproj
- test/Altinn.Platform.Receipt.Tests.csproj
Upgraded from .NET 7 to .NET 8 
- #213
> Upgraded backend to .NET 8 #GCPActive

- src/frontend/src/features/receipt/hooks.ts
- src/frontend/src/language/index.ts
- src/frontend/src/language/languages.ts
- src/frontend/src/language/texts/en.ts
- src/frontend/src/language/texts/nb.ts
- src/frontend/src/language/texts/nn.ts
Fix for the receipt doesn't load if there are no texts for selected language
Fix for the receipt doesn't load if there are no texts for selected language
- #151
> #151 Fix for the receipt doesn't load if there are no texts for selected language

- src/frontend/src/features/receipt/hooks.ts
> #151 Fix the typo for #250

- src/frontend/src/features/receipt/hooks.ts
> #151 Removed resetting the user lang

- src/frontend/src/features/receipt/hooks.ts
Cleaned up all the code added for testing
Removed all the `console.log` which was added to test in the AT environment for lack of support to test in the local environment.
- #151 
- #250 
- #251
> #151 Cleaned up all the code added for testing

- src/frontend/src/features/receipt/hooks.ts
Putting the current language in the beginning.
- #151
> #151 Putting the current language in the beginning.

- .deploy/app.yaml
- .github/workflows/build-and-push-app.yml
- .github/workflows/build-and-push.yml
- Adds a new workflow to build the image, push it to the registry
- the workflow also updates the app configuration and pushes it to the registry (only after the approval)
- uses matrix for the environments for better visualization
- #{issue number}
> chore(CI): add build and push workflow

- .deploy/app.yaml
> chore(ci): add comments in app.yaml

- .github/workflows/build-and-push-app.yml
> chore(cI): fix flux push step

- .github/workflows/build-and-push-app.yml
> chore(ci): fix path for workflow

- .github/workflows/build-and-push-app.yml
> chore(ci): remove wrong arg in flux

- .github/workflows/build-and-push-app.yml
> chore(ci): add OCI annotation to config app artifact

- .deploy/app.yaml
> deploy(app): remove unused value from config

- Dockerfile
Should be fixed now: https://github.com/nodejs/docker-node/issues/2121#issuecomment-2239611865
- #{issue number}
> chore(Dockerfile): upgrade node frontend image

- .github/workflows/build-and-push-app.yml
> chore(CI): add the rest of environments

- .github/workflows/update-chart.yml
> chore(ci): add pr permissions to helm workflow

- .github/workflows/update-chart.yml
> chore(ci): fix format in latest version for helm workflow

- .github/workflows/update-chart.yml
> chore(ci): try to send traces from a workflow

- src/frontend/src/features/receipt/Receipt.test.tsx
- src/frontend/src/features/receipt/Receipt.tsx
- src/frontend/src/features/receipt/hooks.ts
- src/frontend/src/language/texts/en.ts
- src/frontend/src/language/texts/nb.ts
- src/frontend/src/language/texts/nn.ts
- src/frontend/src/types/index.ts
- src/frontend/src/utils/receipt.test.tsx
- src/frontend/src/utils/receipt.ts
Added support for migrated Altinn2 apps
Added support for migrated Altinn2 apps
- #443
> Added support for migrated Altinn2 apps

- .gitattributes
Enforce LF line endings using a .gitattributes file and renormalize existing files with CRLF line endings
https://github.com/Altinn/team-core-private/issues/235
> Introduce end-of-line normalization

- renovate.json
https://github.com/Altinn/team-core-private/issues/271
> Extend renovate config to patch alpine image

- .github/workflows/build-and-analyze.yml
- .github/workflows/frontend-test-build.yml
- src/frontend/package.json
- src/frontend/src/utils/receipt.test.tsx
- src/frontend/src/utils/receipt.ts
Date sent is using the property lastChanged, which will be incorrect in situations where changes are made. The date sent value will be updated to reflect the last time changes were made. In reality, the date sent value should still be the same.
Also updated the build and analyze workflow to include frontend tests in test coverage by running a separate job for *.ts and *.tsx test files
Use process.ended instead of lastChanged
- #479
> Change date sent source from lastChanged to process.ended

- .github/CODEOWNERS
To reduce unwanted notifications from GitHub to everyone on the team
- [323](https://github.com/orgs/Altinn/projects/20/views/11?filterQuery=&pane=issue&itemId=128610640&issue=Altinn%7Cteam-core-private%7C323)
> Limit CODEOWNERS to reduce noise
